global.spesialprem = 'Premium user only bro!'
global.spesialown = 'Owner only bro!'
global.notext = 'teks?'
global.noingroup = 'Only group bro!'
global.nobotadmin = 'Only bot admin bro!'
global.usernoadmin = 'Only admin bro!'
global.gabisafix = 'MAU FIX BUG ? LAWAK DEK²'